version: '3.9'
name: 5400-project

services:
  integration_test:
     
    build: integration_test
      
    volumes:
      - ./test-results:/app/TestResults
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
