name: Client GUI package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client_gui

    steps:
    - uses: actions/checkout@v3
    - name: Build and run GUI service
      run: |
       docker build -f ./ClientGUI/Dockerfile . -t client-gui
       docker run -it --rm -p "32768:80" client-gui
    - name: Unit test with dotnet test
      run: dotnet test "ClientGUI/ClientGUIUnitTesting/ClientGUIUnitTesting.csproj" --logger:trx